name: syzygy
description: Syzygy Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.16.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: main
      path: packages/flame